### ISSUE TITLE
Selecting mail sending option

### ISSUE THREAD

**Issue by syeedtest** [valeriosouza/post-notification#12]
Hi,

By the look of the plugin's option panel, it looks like that it's is programmed to send email when new post/page/comment is published in the site. What i want is, only to send email when a new post is published. If i keep body to page/body to comment/subject to page/ subject to comment fields empty, will it work?

Regards
SC

**Comment by thirtyfiveo** [comment]
@valeriosouza 
Simply leaving the fields empty unfortunately no longer works.
